"""add inventory reservation constraint

Revision ID: 5796e15d2d44
Revises: b195f0ffd0e5
Create Date: 2026-09-22 12:51:59.729245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5796e15d2d44'
down_revision: Union[str, Sequence[str], None] = 'b195f0ffd0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
