"""add order idempotency

Revision ID: 9ac65e71df81
Revises: 9b935e936265
Create Date: 2026-10-05 15:50:11.922812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac65e71df81'
down_revision: Union[str, Sequence[str], None] = '9b935e936265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('idempotency_request_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_orders_customer_id_idempotency_key', 'orders', ['customer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_customer_id_idempotency_key', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_request_hash')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
