"""add inventory transfers

Revision ID: 9b935e936265
Revises: e0b3b4a2216d
Create Date: 2026-10-05 10:47:06.351539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b935e936265'
down_revision: Union[str, Sequence[str], None] = 'e0b3b4a2216d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('transferred_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfers_destination_warehouse_id'), 'inventory_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_id'), 'inventory_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_product_id'), 'inventory_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_reference_id'), 'inventory_transfers', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_source_warehouse_id'), 'inventory_transfers', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_transfers_transferred_by'), 'inventory_transfers', ['transferred_by'], unique=False)
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_order_status_history_changed_by'), table_name='order_status_history')
    op.drop_constraint(op.f('order_status_history_order_id_fkey'), 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('order_status_history_order_id_fkey'), 'order_status_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_order_status_history_changed_by'), 'order_status_history', ['changed_by'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_transfers_transferred_by'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_source_warehouse_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_reference_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_product_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_id'), table_name='inventory_transfers')
    op.drop_index(op.f('ix_inventory_transfers_destination_warehouse_id'), table_name='inventory_transfers')
    op.drop_table('inventory_transfers')
    # ### end Alembic commands ###
